# Generated by Django 3.0.3 on 2020-02-21 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('game_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=15)),
                ('team_city', models.CharField(max_length=25)),
                ('team_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Starters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('away_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_away_1', to='baseball.Players')),
                ('away_10', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_away_10', to='baseball.Players')),
                ('away_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_away_2', to='baseball.Players')),
                ('away_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_away_3', to='baseball.Players')),
                ('away_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_away_4', to='baseball.Players')),
                ('away_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_away_5', to='baseball.Players')),
                ('away_6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_away_6', to='baseball.Players')),
                ('away_7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_away_7', to='baseball.Players')),
                ('away_8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_away_8', to='baseball.Players')),
                ('away_9', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_away_9', to='baseball.Players')),
                ('game_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseball.GameInfo')),
                ('home_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_home_1', to='baseball.Players')),
                ('home_10', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_home_10', to='baseball.Players')),
                ('home_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_home_2', to='baseball.Players')),
                ('home_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_home_3', to='baseball.Players')),
                ('home_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_home_4', to='baseball.Players')),
                ('home_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_home_5', to='baseball.Players')),
                ('home_6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_home_6', to='baseball.Players')),
                ('home_7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_home_7', to='baseball.Players')),
                ('home_8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_home_8', to='baseball.Players')),
                ('home_9', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_home_9', to='baseball.Players')),
            ],
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='away_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_away_team', to='baseball.Teams'),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='home_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_home_team', to='baseball.Teams'),
        ),
    ]
