# Generated by Django 3.0.3 on 2020-02-22 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0003_auto_20200221_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=3)),
                ('half_inning', models.CharField(max_length=4)),
                ('stat_type', models.CharField(max_length=5)),
                ('stat_value', models.IntegerField()),
                ('actual_play', models.CharField(max_length=40)),
                ('num_of_outs', models.IntegerField()),
                ('bases_taken', models.CharField(max_length=3)),
                ('stat_team', models.IntegerField(choices=[('away', 0), ('home', 1)])),
                ('stat_category', models.CharField(choices=[('batting', 0), ('pitching', 1), ('defense', 2)], max_length=8)),
                ('game_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseball.GameInfo')),
                ('player_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseball.Player')),
            ],
        ),
    ]
