# Generated by Django 3.0.4 on 2020-03-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0006_jobrequirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequirements',
            name='year',
            field=models.IntegerField(choices=[(2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010)]),
        ),
    ]
