# Generated by Django 3.0.4 on 2020-04-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0011_auto_20200320_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequirements',
            name='team',
            field=models.CharField(choices=[('ANA', 'ANA'), ('ARI', 'ARI'), ('ATL', 'ATL'), ('BAL', 'BAL'), ('BOS', 'BOS'), ('CHA', 'CHA'), ('CHN', 'CHN'), ('CIN', 'CIN'), ('CLE', 'CLE'), ('COL', 'COL'), ('DET', 'DET'), ('HOU', 'HOU'), ('KCA', 'KCA'), ('LAN', 'LAN'), ('MIA', 'MIA'), ('MIL', 'MIL'), ('MIN', 'MIN'), ('NYA', 'NYA'), ('NYN', 'NYN'), ('OAK', 'OAK'), ('PHI', 'PHI'), ('PIT', 'PIT'), ('SDN', 'SDN'), ('SEA', 'SEA'), ('SFN', 'SFN'), ('SLN', 'SLN'), ('TBA', 'TBA'), ('TEX', 'TEX'), ('TOR', 'TOR'), ('WAS', 'WAS')], max_length=4),
        ),
    ]
