# Generated by Django 3.0.3 on 2020-02-21 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0002_auto_20200221_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='game_id',
            field=models.CharField(max_length=12),
        ),
        migrations.CreateModel(
            name='GamePlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.IntegerField()),
                ('which_half', models.IntegerField(choices=[('away', 0), ('home', 1)])),
                ('half_inning', models.CharField(max_length=4)),
                ('type_of_play', models.CharField(choices=[('play', 'play'), ('sub', 'sub')], max_length=4)),
                ('which_team', models.IntegerField(choices=[('away', 0), ('home', 1)])),
                ('the_play', models.CharField(max_length=40)),
                ('before_1b', models.CharField(max_length=12)),
                ('before_2b', models.CharField(max_length=12)),
                ('before_3b', models.CharField(max_length=12)),
                ('after_1b', models.CharField(max_length=12)),
                ('after_2b', models.CharField(max_length=12)),
                ('after_3b', models.CharField(max_length=12)),
                ('runs_scored', models.IntegerField()),
                ('outs', models.IntegerField()),
                ('batting_spot', models.IntegerField()),
                ('fielding_pos', models.IntegerField()),
                ('game_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseball.GameInfo')),
                ('pitcher_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_pitcher', to='baseball.Player')),
                ('player_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_player', to='baseball.Player')),
            ],
        ),
    ]
