# Generated by Django 3.0.4 on 2020-03-06 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0004_statcollect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameplay',
            old_name='half_inning',
            new_name='half_innings',
        ),
        migrations.RenameField(
            model_name='gameplay',
            old_name='outs',
            new_name='num_of_outs',
        ),
        migrations.AddField(
            model_name='gameplay',
            name='pitch_count',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameplay',
            name='pitches',
            field=models.CharField(default='N', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameplay',
            name='team_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseball.Team'),
        ),
        migrations.AddField(
            model_name='gameplay',
            name='total_scored',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
