# Generated by Django 3.0.4 on 2020-03-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0005_auto_20200306_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[(2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010)], max_length=4)),
                ('team', models.CharField(choices=[('TOR', 'TOR'), ('BOS', 'BOS'), ('ANA', 'ANA'), ('TEX', 'TEX')], max_length=4)),
            ],
        ),
    ]
