# Generated by Django 3.0.4 on 2020-03-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0010_auto_20200318_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequirements',
            name='form_type',
            field=models.CharField(choices=[('import_year', 'import_year'), ('process_team', 'process_team'), ('generate_stats', 'generate_stats'), ('view_stats', 'view_stats')], default=None, max_length=20, null=True),
        ),
    ]
